config/routes.rb
DetSker::Application.routes.draw do
  resources :posts

  devise_for :user
  match 'users/:id' => 'user#destroy', via: :delete, as: :admin_destroy_user
  root 'calendar#index'
  resources :events, except: [:index] do
    member { get 'debug' }
    resources :comments, except: [:new, :delete]
  end
  resources :event_series, controller: :event_series do
    delete 'delete_events', on: :member
  end
  get 'events', to: redirect(path: '/')

  resources :categories
  resources :locations
  resources :users, controller: :user do
    patch 'make_admin', on: :member
  end
  resources :comments

  get 'news' => 'posts#index'
  get 'anonymous_user/new' => 'anonymous_user#new'
  match '/anonymous_user' => 'anonymous_user#create', via: :post
  scope 'admin', controller: :admin do
    get :dashboard, as: :admin_dashboard
    get :series, as: :admin_series
    get :analytics, as: :admin_analytics
    scope 'analytics', controller: :admin do
      get 'timeseries', as: :analytics_timeseries
      get 'events', as: :analytics_events
    end
  end

end

app/views/admin/_event.html.erb
<div class="row">
  <div class="col-md-6">
    <%= "Serie:" if event.event_series.present? %>
    <%= link_to(title_display(event), event) %>
  </div>
  <div class="col-md-6">
    <% if @sort == 'created_at' %>
      <%= "Oprettet for #{link_to(username(event.user), event.user)} #{distance_of_time_in_words(DateTime.now, event.created_at)} siden".html_safe %>
    <% else %>
      <%= "Opdateret for #{distance_of_time_in_words(DateTime.now, event.updated_at)} siden" %>
    <% end %>
  </div>
</div>
<div class="row">
  <hr/>
</div>

app/views/admin/_navigation.html.erb
<%= admin_scripts %>

<div class="container">
  <h1>Administrator Dashboard</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <ul class="list-inline">
        <li>
          <%= link_to('Dashboard', admin_dashboard_path) %>
        </li>
        <li>
          <%= link_to(t('layouts.application.posts'), posts_path) %>
        </li>
        <li>
          <%= link_to(t('layouts.application.users'), users_path) %>
        </li>
        <li>
          <%= link_to(t('layouts.application.categories'), categories_path) %>
        </li>
        <li>
          <%= link_to(t('layouts.application.series'), admin_series_path) %>
        </li>
        <li>
          <%= link_to('Analytics', admin_analytics_path) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/_series.html.erb
<div class="row">
  <div class="col-md-6">
    <%= link_to(title_display(series), series) %>
  </div>
  <div class="col-md-6">
      <%= "Expiry: #{time_ago_in_words(series.expiry)}".html_safe %>
  </div>
</div>
<div class="row">
  <hr/>
</div>

app/views/admin/analytics.html.erb
<%= render partial: 'navigation' %>
<div class="container">
  <div class="row">
    <h1>Analytics Oversigt</h1>
  </div>
<div class="row">
  <div class="col-md-6">
    <h3>Event creation</h3>
    <%= line_chart @events %>
    <h4>
      <%= link_to 'See more', analytics_events_path %>
    </h4>
  </div>
  <div class="col-md-6">
    <h3>Visits by site area</h3>
    <table class="table">
      <thead>
        <tr>
          <th>Action</th>
          <th>Absolute</th>
          <th>Percentage</th>
          <th>Note</th>
        </tr>
      </thead>
      <% @grouped_action.each do |action, values|  %>
        <tr>
          <td><%= link_to(action, analytics_timeseries_path(view: action, interval: 'week')) %></td>
          <td><%= values.first %></td>
          <td><%= "#{values.second.round(2)}%" %></td>
          <td><%= t("analytics.notes.#{action}", default: '') %></td>
        </tr>
      <% end  %>
      <tr>
        <td><%= link_to 'Total', analytics_timeseries_path(interval: 'week') %></td>
        <td><%= @grouped_action.values.collect(&:first).inject(&:+) %></td>
        <td><%= "#{@grouped_action.values.collect(&:second).inject(&:+).round(2)}%"%></td>
      </tr>
    </table>
  </div>
</div>

</div>

app/views/admin/dashboard.html.erb
<%= render partial: 'navigation' %>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <ul class="list-inline pull-right">
        <li><strong>Sortér efter:</strong></li>
        <% AdminController::SORT_TYPES.each do |type| %>
            <%= dashboard_sort_link(type, @sort) %>
        <% end %>
      </ul>
    </div>

  </div>
  <hr/>
  <%= render partial: 'event', collection: @events %>
</div>

app/views/admin/events.html.erb
<%= render partial: 'navigation' %>
<h2>Event creation trends <%= "#{@start_date.strftime('%D')} - #{@end_date.strftime('%D')}" %></h2>
<div class="timeseriesOptions">
  <%= form_tag(analytics_events_path, method: :get, authenticity_token: false) do %>
      <div>
        <label for="start_date">From:</label>
        <%= select_date(@start_date, order: [:day, :month, :year], prefix: :start_date) %>
      </div>
      <div>
        <label for="end_date">Until:</label>
        <%= select_date(@end_date, order: [:day, :month, :year], prefix: :end_date) %>
      </div>
      <%= submit_tag 'Go' %>
  <% end  %>
</div>

<%= line_chart @timeseries %>

<table class="table">
  <thead>
  <tr>
    <th>Visits</th>
  </tr>
  </thead>
  <% @timeseries.each do |date, count|  %>
      <tr>
        <td><%= date %></td>
        <td><%= count %></td>
      </tr>
  <% end   %>
</table>

app/views/admin/series.html.erb
<%= render partial: 'navigation' %>
<div class="container">
    <h2>Events expiring within the next week</h2>
    <%= render partial: 'series', collection: @expiring %>
    <h2>Expired events</h2>
    <%= render partial: 'series', collection: @expired %>
</div>

app/views/admin/timeseries.html.erb
<%= render partial: 'navigation' %>
<h2><%= "#{@view} - #{t("analytics.notes.#{@view}", default: '')}" %></h2>
<div class="timeseriesOptions">
  <%= form_tag(analytics_timeseries_path, method: :get, authenticity_token: false) do %>
    <%= hidden_field_tag :view, @view %>
    <%= label_tag(:interval, 'Interval') %>
    <%= select_tag(:interval, options_for_select(AnalyticsService::VALID_INTERVALS, @interval)) %>
    <%= submit_tag 'Go' %>
  <% end  %>
</div>

<%= line_chart @timeseries %>

<table class="table">
  <thead>
  <tr>
    <th><%= @interval.titleize %></th>
    <th>Visits</th>
  </tr>
  </thead>
  <% @timeseries.each do |date, count|  %>
      <tr>
        <td><%= date %></td>
        <td><%= count %></td>
      </tr>
  <% end   %>
</table>