config/routes.rb
DetSker::Application.routes.draw do
  resources :posts

  devise_for :user
  match 'users/:id' => 'user#destroy', via: :delete, as: :admin_destroy_user
  root 'calendar#index'
  resources :events, except: [:index] do
    member { get 'debug' }
    resources :comments, except: [:new, :delete]
  end
  resources :event_series, controller: :event_series do
    delete 'delete_events', on: :member
  end
  get 'events', to: redirect(path: '/')

  resources :categories
  resources :locations
  resources :users, controller: :user do
    patch 'make_admin', on: :member
  end
  resources :comments

  get 'news' => 'posts#index'
  get 'anonymous_user/new' => 'anonymous_user#new'
  match '/anonymous_user' => 'anonymous_user#create', via: :post
  scope 'admin', controller: :admin do
    get :dashboard, as: :admin_dashboard
    get :series, as: :admin_series
    get :analytics, as: :admin_analytics
    scope 'analytics', controller: :admin do
      get 'timeseries', as: :analytics_timeseries
      get 'events', as: :analytics_events
    end
  end

end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, :short_description, :start_time, :end_time, :location_id, :user_id, :categories, presence: true
  validate :must_be_future_event
  validate :must_be_valid_duration

  belongs_to :user
  belongs_to :location
  belongs_to :event_series
  has_and_belongs_to_many :categories
  has_many :comments
  has_attached_file :picture, styles: { original: '500x500>', thumb: '100x100>'}, default_url: 'images/:st'

  validates_attachment_content_type :picture, :content_type => /\Aimage/
  validates_attachment_file_name :picture, matches: [/png\Z/i, /jpe?g\Z/i]
  validates_with AttachmentSizeValidator, attributes: :picture, less_than:  3.megabytes

  scope :published, -> { where(published: true) }
  scope :future, -> { where('events.end_time > ?', DateTime.now) }
  scope :ordered, -> { order('events.start_time') }
  scope :in_series, -> { where('event_series_id > 0') }
  scope :not_started, -> { where('start_time >= ?', DateTime.now) }
  scope :this_week, -> { where('start_time <= ?', DateTime.now + 6.days) }
  scope :unpublished, -> { future.where(published: false).ordered }
  scope :coming, -> { future.published.ordered }

  def must_be_valid_duration
    return unless end_time.present? && start_time.present?
    unless end_time > start_time
      errors.add(:end_time, I18n.t('events.form.invalid_duration'))
    end
  end

  def must_be_future_event
    return if persisted?
    return unless end_time.present? && start_time.present?
    if start_time < DateTime.now
      errors.add(:start_time, I18n.t('events.form.past_event'))
    elsif end_time < DateTime.now
      errors.add(:end_time, I18n.t('events.form.past_event'))
    end
  end

  def in_progress?
    start_time < DateTime.now && end_time > DateTime.now
  end

  def <=>(other)
    start_time <=> other.start_time
  end

  def description=(val)
    self.short_description = val
  end

  # the name method is an alias used
  # by the page title helper
  def name
    title
  end

  def best_picture
    if picture.present?
      picture
    elsif event_series.present? && event_series.picture.present?
      event_series.picture
    else
      nil
    end
  end

  def has_picture?
    best_picture.present?
  end

  def picture_url
    best_picture.url(:original)
  end

  def weekly?
    event_series.present? && event_series.rule == 'weekly'
  end

  def unpublished?
    !published?
  end

  def self.current_events
    self.includes(:user, :location, :event_series).coming
  end

  def self.main_calendar
    Event.current_non_repeating + Event.current_non_weekly
  end

  def self.current_non_weekly
    self.includes(:user, :location)
      .joins(:event_series)
      .where.not('event_series.rule': 'weekly')
      .coming
  end

  def self.current_non_repeating
    self.includes(:user, :location)
      .coming
      .where(event_series_id: nil)
  end

  def self.featured_events
    self.current_events.where(featured: true).limit(3)
  end

  def self.non_featured_events
    self.current_events
        .where.not(featured: true)
        .where('event_series_id IS NULL')
  end

  def self.latest_added(num)
    num ||= 25
    Event.all.order("created_at DESC").limit(num)
  end

  # Highlights is composed of num events where
  # these are composed of featured events and non-featured events
  def self.highlights(num)
    featured = self.featured_events
    if featured.size < num
      non_featured = self.non_featured_events + self.current_non_weekly
      # we need to sort because we're adding the non_weeklies to the end of the non-featured set
      highlights = (featured + non_featured.sort.take(num - featured.size))
      highlights.uniq.sort
    else
      featured.sort
    end
  end

  # The repeating events that are occurring this week
  def self.repeating_this_week
    self.coming
      .in_series
      .published
      .this_week
      .not_started
      .ordered
  end

  # Return Event object given a Date, Time, Time, attribute Hash
  def self.from_date_and_times(date, start_time, end_time, attributes)
    event_start = DateTime.new(date.year, date.month, date.day, start_time.hour, start_time.min, 0, start_time.zone)
    event_end = DateTime.new(date.year, date.month, date.day, end_time.hour, end_time.min, 0, end_time.zone)
    Event.new(attributes.merge(start_time: event_start, end_time: event_end))
  end

  def to_schema
    {
      '@context': 'http://schema.org',
      '@type': 'Event',
      name: self.title,
      startDate: self.start_time.iso8601,
      endDate: self.end_time.iso8601,
      description: self.short_description,
      sameAs: self.link,
      location: self.location.to_schema,
      organizer: self.user.to_schema
    }
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :debug]
  before_action :set_presenter, only: [:show]
  #TODO: shouldn't we authenticate the user before the create action also?
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :authorised_user?, only: [:edit, :update, :destroy]

  def show
  end

  def debug
  end

  def new
    @event = Event.new
  end

  def create
    event_params = user_params
    # add the user id if we've got one
    event_params.merge!(user_id: current_user.id) if user_signed_in?
    # handle creation of recurring events here
    if params[:recurring] == 'yes'
      series_params = event_params.merge(event_params[:event_series]).except(:event_series, :featured)
      @event_series = EventSeries.new(series_params)
      saved = @event_series.save
      notice = I18n.t('event_series.created', link: url_for(@event_series), name: @event_series.name, num_events: @event_series.coming_events.size)
    else
      @event = Event.new(event_params.except('event_series'))
      saved = @event.save
      notice = I18n.t('events.event_created', link: url_for(@event), name: @event.name)
    end

    respond_to do |format|
      if saved
        format.html { redirect_to root_path, notice: notice }
        format.json { render action: 'show', status: :created, location: @event }
      elsif @event_series.present?
        format.html { render template: 'event_series/new' }
        format.json { render json: @event_series.errors, status: :unprocessable_entity }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(user_params)
        destroy_image?
        format.html {
          redirect_to root_path, notice: I18n.t('events.event_updated', link: url_for(@event), name: @event.name)
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: I18n.t('events.event_deleted') }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_presenter
    @event_presenter = EventPresenter.new(@event, view_context)
  end

  def authorised_user?
    unless current_user.can_edit? @event
      redirect_to root_path, alert: I18n.t('general.permission_denied')
    end
  end

  # if the obj has a picture but it's not in the new form
  def destroy_image?
    if @event.picture.present? && params[:remove_picture] == '1'
      @event.picture.clear
      @event.save
    end
  end

  def user_params
    params.require(:event).permit(:title, :short_description, :long_description,
                                 :start_time, :end_time,  :location_id, :comments_enabled,
                                 :price, :cancelled, :link, :picture, :featured, :published,
                                 category_ids: [], event_series: [[:rule, :start_date, 
                                 :start_time, :expiry, :end_time, day_array: []]]).tap do |list|
      list[:category_ids].uniq!
      list[:event_series][:days] = list[:event_series][:day_array].select(&:present?).join(',') if list[:event_series].present? && list[:event_series][:day_array].present?
      list.delete(:featured) unless current_user.is_admin? # only admins can update featured value
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  # included to fix bug in content_tag generation
  include ActionView::Context
  # necessary as events.js.erb will call this
  # Helper during precompile
  include ActionView::Helpers::FormHelper

  def format_datetime(dt)
    I18n.localize(dt, format: :calendar)
  end

  def format_daterange(starttime, endtime)
    # If it's the same day, only print day once
    if starttime.to_date == endtime.to_date
      "#{I18n.localize(starttime, format: :calendar)} - #{I18n.localize(endtime, format: :time)}"
    else
      "#{I18n.localize(starttime, format: :calendar)} - #{I18n.localize(endtime, format: :calendar)}"
    end
  end


  def format_starttime(dt)
    dt.strftime('%H:%M')
  end

  def format_date(d)
    I18n.localize(d, format: :header)
  end

  def title_display(event)
    if event.cancelled?
      "<s>#{event.title}</s> - <span class='text-danger'>#{I18n.t('events.event.cancelled')}</span>".html_safe
    else
      event.title
    end
  end

  def categories_as_string(categories, title = false)
    categories.map { |cat| transl_cat(cat) }.join(' ')
  end

  # Return the current language string for a category
  # @param cat Category | String (id)
  def transl_cat(cat)
    cat = Category.find(cat) unless cat.is_a? Category
    cat.send(t :language).titleize
  rescue
    ''
  end

  def render_filter_link(id, name, total, type)
    link_to "#{name} (#{total})", '',
            data: { toggle: id, filter_type: type,
                    role: 'filter-link'
            }
  end
  def display_repetition_rule(series)
    # translate the days and convert them to a string
    transl_days = series.day_array.collect { |d| I18n.t("day_names.#{d.titleize}", default: d) }.to_sentence(locale: I18n.locale)
    if series.rule == 'weekly'
      I18n.t('event_series.weekly_display_rule', days: transl_days)
    elsif series.rule == 'biweekly_odd'
      I18n.t('event_series.biweekly_odd_display_rule', days: transl_days)
    elsif series.rule == 'biweekly_even'
      I18n.t('event_series.biweekly_even_display_rule', days: transl_days)
    else
      transl_rule = I18n.t("event_series.#{series.rule}", default: series.rule)
      I18n.t('event_series.monthly_display_rule', days: transl_days, rule: transl_rule)
    end
  end

  # A category tag is composed of two elements
  # a hidden input field and a bootstrap label
  # The input is connected to the label via a
  # javascript listener, so that it will be removed
  # when the label is removed.
  # This function is to be shared between html and js views
  # In the case of js views, we can't pass the variables, therefore
  # we give a default value which can be overwritten.
  def category_tag(cat_id = '_id_', value = '_value_')
    bootstrap_label(cat_id, value) + category_input(cat_id)
  end

  def category_input(val)
    hidden_field_tag(val, val, name: 'event[category_ids][]', data: { role: 'category_value' } )
  end

  def dayname_collection
    names = Date::DAYNAMES.dup
    names << names.delete_at(0) # move sunday to the end!
    names.collect {|n| [t("day_names.#{n}"), n]}
  end


  def bootstrap_label(id, value)
    # we create the content in two steps to make the nested value
    # output correctly
    content = value
    content << content_tag(:a, data: { function: 'remove_category', target: id }) do
      content_tag(:span, '', class: 'remove glyphicon glyphicon-remove glyphicon-white')
    end

    content_tag(:span, class: 'tag label label-primary') do
      content.html_safe
    end
  end

  def typeahead_header(text = '_value_')
    content_tag(:div) do
      content_tag :strong, class: 'use-styles' do
        text
      end
    end
  end

  def typeahead_element(text = '_value_')
    content_tag(:div) do
      content_tag(:span, class: 'use-styles') do
        text
      end
    end
  end

  # Generic method to create glyphicon icons
  # supply only the last component of the icon name
  # e.g. 'off', 'cog' etc
  def bootstrap_glyphicon(icon, classes = '')
    html_class = ['glyphicon', "glyphicon-#{icon}", classes].select(&:present?).join(' ')
    content_tag(:span, nil, class: html_class, 'aria-hidden': true).html_safe
  end

  def bootstrap_success(message)
    bootstrap_alert(message, 'success')
  end

  def bootstrap_danger(message)
    bootstrap_alert(message, 'danger')
  end

  def bootstrap_info(message)
    bootstrap_alert(message, 'info')
  end

  def bootstrap_alert(message, level)
    content_tag(:div, message.html_safe, class: "alert alert-#{level}", role: 'alert')
  end

  # return json ld of object schema microdata
  def schema_json(object)
    details = object.to_schema
    case object
     when Event
      url = event_url(object)
      # we add the picture url here so that we can create a url
      details.merge!(image: image_url(object.best_picture.url(:original))) if object.best_picture.present?
      when User
        return if object.is_anonymous?
        url = user_url(object)
      when Location
        url = location_url(object)
      else
        return
    end
    details.merge!(url: url)
    content_tag(:script, details.to_json.html_safe, type: 'application/ld+json')
  end

  def image_url(file)
    request.protocol + request.host_with_port + file
  end
end

app/views/events/_card.html.erb
<div class="card" href="#">
    <div class="card__layout">
        <div class="card__media">
            <%= presenter.picture_tag %>
        </div>
        <div class="card__text">
            <div class="card__header">
                <div class="card__date">
                    <%= presenter.date %>
                </div>
                <div class="card__place">
                    <%= presenter.location %>
                </div>
            </div>
            <div class="card__main">
                <h1 class="card__title">
                    <%= presenter.title %>
                </h1>
                <%= presenter.teaser %>
                <div class="card__more">
                    <%= presenter.more_description %>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="card__toggle js-toggle-card"></a>
</div>

app/views/events/_event.html.erb
<%
   data_attrs = {
    categories: event.categories.collect(&:id).join(' '),
    location: event.location.display_name.parameterize(separator: '_'),
    role: 'event'
   }
%>
<%  data_attrs.merge!(rule: 'weekly') if event.weekly?  %>
<%  data_attrs.merge!(parent: parent_id.to_s) if defined? parent_id %>

<%= content_tag :div, class: 'event-container row', data: data_attrs do %>

  <%= schema_json(event) %>
  <%# In mobile view the title line is broken up into two lines %>
  <span class="col-xs-12 col-md-6 col-md-push-2 event-title">
      <%= link_to(title_display(event), event) %>
  </span>

  <span class="col-xs-2 col-md-2 col-md-pull-6">
    <%# In the frontpage context we don't show a date, otherwise, do. %>
    <% if defined? show_date %>
        <%= I18n.localize(event.start_time.to_date, format: :brief)  %>
    <% else %>
        <%= format_starttime(event.start_time) %>
    <% end %>
  </span>

  <span class="col-md-2 hidden-xs categories">
    <%= categories_as_string(event.categories) %>
  </span>
  <span class="col-md-2 pull-right">
  <a href="<%= url_for(event.location) %>"title="<%= event.location.description.truncate(120) %>"
     data-toggle='popover' data-placement='top' data-trigger="click hover focus" data-html="true">
    <%= event.location.display_name %>
  </a>
  </span>

<% end %>

app/views/events/_form.html.erb
<%= simple_form_for @event, html: { multipart: true } do |f| %>


<div class="row">
  <div class="col-xs-12">
    <%= f.input :title %>
  </div>
</div>
<% if @event.persisted? %>
<div class="row">
  <div class="col-xs-12">
    <%= f.input :cancelled, wrapper_html: { class: 'checkbox' },
    input_html: { class: 'checkbox'}, label_html: { class: 'override'} %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= f.label :picture %>
    <span class="btn btn-default btn-file">
      <span id="js_button_text">
        <%# show the filename in the button if there is a file %>
        <% if @event.picture.present? %>
        <%= @event.picture.original_filename %>
        <% else %>
        <%= t '.choose_file' %>
        <% end %>
      </span>
      <%= f.input :picture, label: false %>
    </span>
    <%= bootstrap_glyphicon('trash', 'btn btn-default') if @event.picture.present? %>
    <input type="hidden" name="remove_picture" id="event_remove_picture"/>
    <br/>
    <br/>
    <%= f.hint t('.picture.warning'), data: { role: 'picture_warning' } %>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= f.input :short_description %>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-5">
    <%= f.association :categories, label_method: ->(obj){ obj.send(t(:language)).titleize }, required: true,
    input_html: { class: 'selectpicker', title: t('.choose_category') }
    %>
  </div>
  <div class="col-xs-12 col-sm-5 col-sm-offset-1">
    <%= f.label :location_id %>
    <%# If we already have a location the placeholder should be that location's name %>
    <% location_name = @event.location.display_name rescue nil %>
    <%= text_field_tag(
      'location-typeahead', location_name,
      placeholder: "#{location_name || t('.choose_location')}",
      class: "typeahead form-control",
        data: {
          api_path: locations_path,
          remote_path: new_location_path,
          label: t('.create_location'),
          display_key: 'display_name',
          header: t('.typeahead_header'),
          target: '#event_location_id',
          empty_message: t('.empty_location')
        }
        )
        %>
        <%= f.full_error :location_id %>
        <%= link_to new_location_path, class: 'btn btn-default btn-sm pull-right',
        data: {
          remote: true,
          toggle: 'modal',
          target: 'remote_form_modal',
          update_val: '#location-typeahead',
          update_field: 'event[location_id]',
          modal_title: t('.new_location_title')
        } do %>
        <%= t('.create_location') %>
        <%= bootstrap_glyphicon('plus') %>
        <% end %>

        <%= f.input :location_id, as: :hidden %>

      </div>
    </div>

    <%# This dialog is only for new events %>
    <% unless @event.persisted? %>
      <div id='check_recurring' class="checkbox">
        <label>
          <%= check_box_tag :recurring, 'yes', false,
          data: { function: 'show', target: '#repeating_control', hide: '#standard_time_control' }
          %>
          <%= t '.repeating_event' %>
        </label>
      </div>

      <div id="repeating_control" class='form-inline row-fluid' style="display: none;">
        <h2><%= t 'event_series.form.repetition_header' %></h2>
        <%= f.simple_fields_for :event_series do |s| %>
         <%= render partial: 'event_series/repeating_control', locals: { builder: s,  coming_events: false } %>
        <% end %>
      </div>
    <% end %>


     <div id="standard_time_control" class="row">
      <%= f.input :start_time, start_year: Date.today.year, end_year: Date.today.year + 1, minute_step: 15 %>
      <%= f.input :end_time, start_year: Date.today.year, end_year: Date.today.year + 1, minute_step: 15 %>
      </div>

     <div class="row">
      <div class="col-xs-12">
        <%= f.input :link, as: :url %>
      </div>
    </div>

    <%# event price field should only be shown a) if there is already a price
    or b) if the user has checked this box to say that there is a price
    Note the javascript hooks on the data elements. %>
    <% if @event.price.blank? %>
    <div class="input boolean optional event_price_enabled checkbox">
      <label class="boolean optional control-label override checkbox" for="event_price_enabled">
        <input class="boolean optional checkbox" id="event_price_enabled"
        name="event[price_enabled]" value="1" type="checkbox"
        data-function="show" data-target=".event_price">
        <%= t '.enable_price' %>
      </label>
    </div>
    <% end %>

    <% if current_user.is_admin? %>
    <div class="input boolean optional checkbox">
      <label class="boolean optional control-label override checkbox" for="event_featured">
      <%= f.input_field :featured, boolean_style: :inline, class: 'checkbox no-form-control' %>
      <%= t '.feature_event?' %>
      </label>
    </div>
    <% end %>

    <div class="row">
      <div class="col-xs-12">
        <% visibility =  @event.price.present? ? 'block' : 'none' %>
        <%= f.input :price, wrapper_html: { style: "display: #{visibility}"} %>
      </div>
    </div>
    <div class="input boolean optional event_comments_enabled checkbox">
      <label class="boolean optional control-label override checkbox" for="event_comments_enabled">
        <%= f.input_field :comments_enabled, boolean_style: :inline, class: 'checkbox no-form-control' %>
        <%= t 'simple_form.labels.defaults.comments_enabled' %>
      </label>
    </div>
    <div class="input boolean optional checkbox">
      <label class="boolean optional control-label override checkbox" for="event_published">
        <%= f.input_field :published, boolean_style: :inline, class: 'checkbox no-form-control' %>
        <%= t 'simple_form.labels.defaults.published' %>
      </label>
      <span class="text-info">
        <%= t('simple_form.labels.defaults.published_help') %>
      </span>
    </div>
    <br/>
    <div class="row">
      <div class="col-xs-12">
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
    <br/>
    <% end %>
    <%= render partial: 'layouts/modal_wrapper' %>

app/views/events/debug.html.erb
<% no_index_rule %>
<div class="container">
  <div class="event_show">
    <h1>Debug View</h1>
    <h2>Timing</h2>
    <table class="table">
      <tr>
        <td>Current time</td><td><%= DateTime.now %></td>
      </tr>
      <tr>
        <td>Event start</td><td><%= @event.start_time %></td>
      </tr>
      <tr>
        <td>Event end</td><td><%= @event.end_time %></td>
      </tr>
    </table>
    <h2>Event Details</h2>
    <code>
      <%= @event.to_json.gsub(',"', ",<br/>").html_safe %>
    </code>
  </div></div>

app/views/events/edit.html.erb
<div class="event_form">
<h1><%= t '.edit_event' %></h1>
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/new.html.erb
<div class="event_form">
<h1><%= t '.new_event' %></h1>
<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>

app/views/events/show.erb
<% content_for :meta_tags do %>
  <%= @event_presenter.fb_tags  %>
<% end %>
<%= schema_json(@event) %>
<div class="event_show">
  <% if @event.unpublished? %>
    <% no_index_rule %>
    <%= bootstrap_info(t('.unpublished_explanation')) %>
  <% end %>
  <h1><%= @event.title %></h1>
  <%# If this event has a picture, show that, if not and it's part of a series with a picture, show that instead %>
  <% if @event.best_picture.present? %>
    <%= image_tag @event.best_picture.url(:original), title: @event.title, alt: @event.title %>
  <% end %>
  <h3>
    <%= format_daterange(@event.start_time, @event.end_time) %>
  </h3>
  <h4> 
    <%= link_to(@event.location.full_address, location_path(@event.location)) %>
  </h4>
  <p>
  <%= "#{t('events.event.posted_by')} #{link_to(username(@event.user), @event.user)  if @event.user}".html_safe %>
  </p>

  <% if @event.price.present? %>
      <p><strong><%= t 'simple_form.labels.event.price' %>: </strong><%= @event.price %></p>
  <% end %>
  <p><%= link_to(display_repetition_rule(@event.event_series), @event.event_series) if @event.event_series.present? %></p>
  <p>
    <%= auto_link(simple_format(@event.short_description)) %>
    <%= auto_link(simple_format(@event.long_description)) %>
  </p>

  <p>
    <%= link_to(t('events.event.download_ics'), event_path(@event, format=:ics))%>
  </p>

  <% if @event.link.present? %>
      <p>
        <%= link_to(t('.link'), @event.link) %>
      </p>
  <% end %>

  <% if current_user && current_user.can_edit?(@event) %>
      <%= link_to t(:edit), edit_event_path(@event) %> |
      <%= link_to t(:delete), event_path(@event), method: :delete, data: { confirm: t('.delete_warning') } %>
  <% end %>
   <% if current_user && @event.event_series.present? && current_user.can_edit?(@event.event_series) %>
    <hr/>
    <div class="hidden-xs">
      <%= link_to t('event_series.edit_link'), edit_event_series_path(@event.event_series) %> 
      <br/>
      <%= link_to t('event_series.delete_events_link'), delete_events_event_series_path(@event.event_series), method: :delete, confirm: t('event_series.delete_events_warning', number: @event.event_series.events.size) %> 
    </div>
  <% end %>
  <% if @event.comments_enabled? %>
        <hr/>
        <%= render partial: 'events/comments/list', locals: { comments: @event.comments } %>
        <%= render partial: 'comments/form', locals: { event: @event, show_form: false } if user_signed_in? %>
  <% end %>
  <% if current_user && current_user.is_admin?  %>
    | <%= link_to('Debug', debug_event_path(@event))   %>
  <% end %>

</div>

app/views/events/show.ics.erb
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//<%= t('events.ics.prodid') %>
X-WR-CALNAME:<%= t('events.ics.prodid') %>
X-WR-TIMEZONE:"UTC"
BEGIN:VEVENT
DTSTAMP:<%= DateTime.now.strftime('%Y%m%dT%H%M%SZ') %>
UID:<%= @event.id %>
DTSTART:<%= @event.start_time.utc.strftime('%Y%m%dT%H%M%SZ') %>
DTEND:<%= @event.end_time.utc.strftime('%Y%m%dT%H%M%SZ') %>
SUMMARY:<%= @event.title %>
DESCRIPTION:<%= @event.short_description %>
<%= @event.long_description %>
LOCATION:<%= @event.location.full_address %>
END:VEVENT
END:VCALENDAR