config/routes.rb
DetSker::Application.routes.draw do
  resources :posts

  devise_for :user
  match 'users/:id' => 'user#destroy', via: :delete, as: :admin_destroy_user
  root 'calendar#index'
  resources :events, except: [:index] do
    member { get 'debug' }
    resources :comments, except: [:new, :delete]
  end
  resources :event_series, controller: :event_series do
    delete 'delete_events', on: :member
  end
  get 'events', to: redirect(path: '/')

  resources :categories
  resources :locations
  resources :users, controller: :user do
    patch 'make_admin', on: :member
  end
  resources :comments

  get 'news' => 'posts#index'
  get 'anonymous_user/new' => 'anonymous_user#new'
  match '/anonymous_user' => 'anonymous_user#create', via: :post
  scope 'admin', controller: :admin do
    get :dashboard, as: :admin_dashboard
    get :series, as: :admin_series
    get :analytics, as: :admin_analytics
    scope 'analytics', controller: :admin do
      get 'timeseries', as: :analytics_timeseries
      get 'events', as: :analytics_events
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include HasEvents
  apply_simple_captcha

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  alias_method :user_id, :id

  validates :username, presence: true, uniqueness: true
  validates_confirmation_of :email, message: I18n.t('user.email_must_match')
  validates_presence_of :email_confirmation, on: :create, unless: :is_anonymous?
  # ensure user is permitted to edit object
  # either if the user is an admin or if
  # the user has created the object
  # Note only event objects have user_ids
  def can_edit?(object)
    self.is_admin? || id == object.try(:user_id)
  end

  def make_admin
    self.is_admin = true
    self.save
  end

  # the name method is an alias used
  # by the page title helper
  def name
    username
  end

  def to_schema
    unless self.is_anonymous?
      {
        '@context': 'http://schema.org',
        '@type': 'Person',
        name: self.username,
        description: self.description
      }
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :make_admin]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :make_admin]
  before_action :authorised_user?, only: [:edit, :update, :destroy]
  before_action :admin_user?, only: [:make_admin, :destroy]

  # We don't do the case insensitive search
  # in SQL as it is implementation dependent,
  # i.e. different from sqlite3 to postgres.
  # Therefore we do an initial sort in sql
  # and a subsequent one in Ruby.
  def index
    @users = User.where(is_anonymous: false).order(:username).sort_by { |u| u.username.downcase }
  end

  def new
  end

  def create
  end

  def show
    @calendar = Calendar.with_hidden(@user)
  end

  def edit
  end

  def update
    if @user.update(user_whitelist)
      redirect_to @user, notice: I18n.t('layouts.updated.basic_message')
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: 'User deleted'
    else
      redirect_to :back, status: :service_unavailable
    end
  end

  def make_admin
    if @user.make_admin
      redirect_to users_path, notice: "User #{@user.username} is now an admin user"
    else
      redirect_to users_path, alert: 'Error! User could not be updated...'
    end
  end

  private
  def authorised_user?
    unless current_user.can_edit? @user
      redirect_to users_path, notice: 'You are not permitted to edit this user!'
    end
  end

  def admin_user?
    unless current_user.is_admin?
      redirect_to users_path, notice: 'Only admin users can perform this action!'
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_whitelist
    params.require(:user).permit(:email, :password, :username, :is_admin, :description)
  end
end

app/views/user/_user.html.erb
<div>
  <p><%= link_to(user.username, user_path(user)) %>
  <%= 'Admin' if user.is_admin? %>
  <%= bootstrap_glyphicon('question-sign') if user.confirmed_at.nil? %>
  </p>
</div>

app/views/user/edit.html.erb
<div class="generic_form">
<h2><%= @user.username %></h2>
<%= simple_form_for @user do |f| %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>
</div>

app/views/user/index.html.erb
<% @users.each do |user| %>

  <%= render partial: 'user', object: user %>

<% end %>

app/views/user/show.html.erb
<% if @user.is_anonymous? %>
  <% no_index_rule %>
<% else %>
  <% user_metadata(@user) %>
<% end %>
<div class="event_show">
  <h2><%= @user.username %></h2>
  <p><%= "#{t('member_since')}: #{format_date(@user.created_at.to_date)}" %></p>
  <p><%= @user.description %>
    <%# Allow editing for that user if they are logged in %>
  <p><%= link_to t(:edit), edit_user_path(@user) if (current_user && current_user == @user) %></p>
  <% if current_user && current_user.is_admin? %>
      <p><%= "Email: #{auto_link(@user.email)}".html_safe %></p>
      <%# If user is unconfirmed allow them to be deleted (e.g. accounts created with incorrect emails) %>
      <% if @user.confirmed_at.nil? %>
          <p><%= t('.unconfirmed') %></p>
          <p>
            <%= button_to('Delete user', admin_destroy_user_path(@user), method: :delete,
                           data: { confirm: 'Are you sure you want to delete this user?'}) %>
          </p>
      <% end %>
      <% unless @user.is_admin? || @user.is_anonymous? %>
          <p>
            <%= button_to('Make Admin User', make_admin_user_path(@user),
                           method: :patch, data: { confirm: 'Are you sure?' }) %>
          </p>
      <% end %>
  <% end %>
  <hr/>
  <div>
    <h2><%= t :coming_events %></h2>
    <% if @calendar.in_progress.size > 0 %>
        <%= render partial: 'calendar/day', object: @calendar.in_progress, locals: { id: 'inProgress' } %>
    <% end %>
    <%= render partial: 'calendar/day', collection: @calendar.days  %>
  </div>
</div>